### ISSUE TITLE
Transferir textos para a Wiki

### ISSUE THREAD

**Issue by Raphael-18** [Raphael-18/projeto-de-pesquisa#5]
Conforme avançar o relatório de acompanhamento de bolsa, transferir as revisões bibliográficas dos métodos (SMAP, muskingum de montante e de jusante) para a Wiki do projeto.

**Comment by joaotercini** [comment]
Ter a biblioteca mermaid para fluxogramas https://mermaid.live/


> mermaid
>graph TD
>    A[Christmas] -->|Get money| B(Go shopping)
>    B --> C{Let me think}
>    C -->|One| D[Laptop]
>    C -->|Two| E[iPhone]
>    C -->|Three| F[fa:fa-car Car]
>

``` mermaid
graph TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]
```

**Comment by Raphael-18** [comment]
Acredito que todas as seções foram atualizadas. Fechando o issue.
